(ns test.carly.clojure-test
  "Integration code for wedding generative test.check functions to clojure.test
  assertion macros."
  (:require
    [clojure.test.check :as tc]
    [clojure.test :as ctest]
    [puget.printer :as puget]))


; TODO: affordance for setting pretty-printer handlers


(defmethod ctest/report ::shrunk
  [result]
  (newline)
  (printf "Tests failed with seed %s - smallest case:\n" (:seed result))
  ; TODO: more shrink stats
  (prn (dissoc (:shrunk result) :smallest))
  (puget/cprint (get-in result [:shrunk :smallest])))


(defmacro capture-reports
  "Capture any clojure.test reports generated by the body."
  [& body]
  `(let [reports# (atom [])]
     (binding [ctest/report (partial swap! reports# conj)]
       ~@body)
     @reports#))


(defn publish!
  "Publish a collection of reports to clojure.test."
  [reports]
  (run! ctest/report reports))


#_
(defmacro check-and-report
  [message num-tests-or-options bindings & body]
  `(ctest/testing ~message
     (let [final-reports# (atom [])]
       ; TODO: run tests...
       (run! ctest/report @final-reports#))))
